// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = import.meta.env.VITE_SUPABASE_URL;
const SUPABASE_PUBLISHABLE_KEY = import.meta.env.VITE_SUPABASE_PUBLISHABLE_KEY || import.meta.env.VITE_SUPABASE_ANON_KEY;

// "Remember me" support: if rememberMe is set to "false", use sessionStorage so the session ends when the browser closes.
const REMEMBER_ME = typeof window !== 'undefined' ? localStorage.getItem('rememberMe') !== 'false' : true;
const AUTH_STORAGE = typeof window !== 'undefined' ? (REMEMBER_ME ? localStorage : sessionStorage) : undefined as any;

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: AUTH_STORAGE,
    persistSession: true,
    autoRefreshToken: true,
  }
});